### PR TITLE
Enduser identify api

### PR DESCRIPTION
**Pull request by fmauchle**
After woking with the admin (silverbullet) API for some time, I noticed some inconveniences and missing parts which I tried to address:

1. The result of enduser-identify has the same information as eg. enduser-new, but uses a different format. Align those formats.
2. Enduser-identify always queries the complete user list from the DB and searches that result manually; let SQL do that searching.
3. Add certificate-CN as search option for enduser-identify
4. Remove the certificate type when querying for a silverbullet certificate by CN; the CN is already guaranteed to be unique by the code creating it. This makes searching for a certificate/user much easier if only the CN is known, but not the certificate type - which is the typical case when only information of radius logs are available.

### CODE REVIEW

**Comment by restena-sw** [comment]
Thanks for this work! It's almost good for merging. There is only one thing that is currently suboptimal: the constructor to SilverbulletCertificate has the caType as second parameter. In your code, you call the constructor with "" as parameter value because it is not needed for the particular use you need the object for.
Still, the constructor places the caType into the member variable $this->ca_type (line 84). There are 15 references where this member variable is actively used elsewhere in the code - callers typically expect the field to be properly populated after creation.

Can you modify your code to 
a) formally make that second constructor parameter optional. 
b) in case it is not supplied, look up the CA type from database and populate $this->ca_type from that lookup
?

That makes the code a lot cleaner at that spot. If you find the time, optionally fix the two Scrutinizer issues (parameter not in phpdoc).

**Comment by fmauchle** [comment]
> b) in case it is not supplied, look up the CA type from database and populate $this->ca_type from that lookup

good catch. Should we actually handle this the same as all other fields and always fetch it from the db?

**Comment by restena-sw** [comment]
You are right. Since the username is always unique, regardless of CA type chosen, constructing the object with this second parameter is always redundant.
So yes, please go ahead and modify the constructor (and all its callers) to work with just one parameter only.

**Comment by restena-sw** [comment]
Does this really work? ca_type is unconditionally present in the SQL query in the WHERE clause. Whem omitting the parameter, this doesn't find the cert due to an = NULL check?

**Comment by fmauchle** [comment]
there are 2 queries:
1. if $identifier is numeric (a serial) ca_type must be supplied in the where clause, as the serial is not globally unique (only within ca_type)
2. else $identifier is a CN and ca_type is not required in the where clause as it is globally unique

**Comment by restena-sw** [comment]
Nice! Thanks for the explanation. I'm merging this now.

**Pull request merged**
