### PR TITLE
Test Linux installer on newer platforms

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Comment by restena-sw** [comment]
Thanks for this!

Unfortunately it is mostly a duplication... we changed the GitHub actions in release_2_1 already, which will be synced with master later on.

Accepting your PR as-is would introduce merge conflicts. Please review our changes in release_2_1 instead and see if you find items still in need to changing. It's then best to make a PR on that branch.

**Comment by DimitriPapadopoulos** [comment]
Also, this is not really duplication.

* Under `python_linting`:
   * `python-version: [3.9]` -> `python-version: ["3.10"]`
* Under `test_ubuntu`:
  * `os: [ubuntu-18.04, ubuntu-20.04]` -> `os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]`
  * `python-version: [3.6, 3.7, 3.8, 3.9]` -> `python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]`

**Comment by restena-sw** [comment]
That's why I wrote to please check if some things are still missing :-)

release_2_1 is now merged, you can work against master now.

**Comment by restena-sw** [comment]
Hm, I can't reopen the PR because your branch "was force-pushed or recreated". You may need to make a new PR.

**Pull request closed without merging**
