### PR TITLE
Add linux bash installer

### PR DESCRIPTION
**Pull request by ikreb7**
Hello @twoln,

here is my first draft. A lot of code should be known for you. I will do soon more, but you could already give me feedback so I could improve problems.

### CODE REVIEW

**Comment by ikreb7** [comment]
Thank you for merging. What are the next steps? Should I modify ``DeviceLinux.php``?

**Comment by twoln** [comment]
I suggest to leave DeviceLinux intact but create DevieceLinuxSh instead. I really want to have the working solution in parallel to the new one. They can live next to each other without a problem.
The bash script you created needs to be created dynamically with appropriate certificates, messages in correct language etc. I would say that what you now have is a good thing to model things on but DeviceLinuxSh will just need to create the script. This can be cone in a multiple of ways, combining several files for instance, so some of them can by staic. 
Do you have access to my newest DeviceLinux version that was creating the bash script?

**Comment by ikreb7** [comment]
Yes, to use it parallel sounds good.

No, maybe you could sent it me by mail or push it in the git, please.

**Comment by twoln** [comment]
I will upload the module tomorrow.

**Comment by twoln** [comment]
I have added the olde device updating it so that it actually generates the script, but it definitely needs testing that it actually works. The next step would be to replace the bus parts with nmcli from your script. Perhaps it would be wise to extract the static part of the sh script into the Files and then produce the variable part with php finally combining them into the final installer file. Windows device does that using the temporary directory. Doing so might make DeviceLinuxSh a lot more readable. It must be remembered that we need to add the user certificate support as required by ManagedIdP.

**Comment by ikreb7** [comment]
My latest commits are not connected with this PR because you closed the issue. I will create a new PR for further work.

**Pull request merged**
