### PR TITLE
Add IWD support

### PR DESCRIPTION
**Pull request by ikreb7**
Hello @twoln ,

I think we should further test iwd, but since some people already use it, we could offer the configurations in the python code yet. 

I could do more. But we have to discuss at first how we decide when we use `wpa_supllicant` or `iwd`?

### CODE REVIEW

**Comment by twoln** [comment]
So at this level it is just the class definition without any actual calls to it?

**Comment by ikreb7** [comment]
> So at this level it is just the class definition without any actual calls to it?

Yes. I already wrote you that I want to discuss with you how we could make the switch between wpa_supplicant and iwd.

**Comment by twoln** [comment]
If this is OK with you I will just merge this PR and we can discuss the rest of the stuff later?

**Comment by ikreb7** [comment]
Ok. We could discuss this at #201 .

**Pull request merged**
