### PR TITLE
Add interactive mode

### PR DESCRIPTION
**Pull request by ikreb7**
We use this mode to test interactive the linux installer with docker and a lot of linux distros. It would be nice if you could add this so that our code is synchronous with our code.

With this pull request, you have the parameter ``-d/--debug``, ``-y/--yes``, ``-u/--username`` and ``-p/--password``.

It would be nice if you could merge the pull request instead of copy and paste my code by the way. There wouldn't be a difference.

### CODE REVIEW

**Comment by twoln** [comment]
Actually the changes suggested by you guys made me take another look at the code as a whole and realise that the organisation of the flow has a problem. It does not make sense to ask the user for credentials only to tell him afterwards that we cannot do anything for him since the connection to NM failed. That made me to do some rearrangements. Also running the code trough pylint suggested naming changes (these also appeared in one of the pull requests). I did not push these to GitHub yet as Stefan and I need to decide if we really want to put in such a change at this stage of the project release.
Due to that it may be a bit harder to just pull in your changes automatically. Adding argparse is on my radar - that is also in one of the outstanding pull requests.

**Comment by twoln** [comment]
I decided to leave the current main.py for now while pushing main_new.py with a rewrite of the workflow, change of variable and method naming, blocking messages from zenity etc. This file should get a proper testing and a closer look by the current contributors. I will go trough the pull requests again and try to incorporate all suggestions. I will be much more open towards merging changes to this file.
In order to get this file being used in installer generation one needs to make change the call to main.py to main_new.py in Device_Linux.php. Of course this is only temporary and due to the fact that we are in the beta phase.

**Comment by twoln** [comment]
So the assumption is that non-interactive mode will only work inn the tty mode? This makes sense, I guess. 
There is one think I am not very happy about. prompt_nonempty_string is meant to be a universal method even if it is now only used for username and password. At the moment with the password argument set it will just exit.
I would suggest adding a -b/--batch flag and just use this, it would also open a path for automatic installation without username and password. Those would be prompted by the system. This way you could set up machines leaving the actual authentication to the user at the first connection.

**Comment by twoln** [comment]
So I have added -s/--silent mode to the installer. If you do not set -u and/or -p then they will not get set. I have dropped -y, this did not seem to be really useful it is just assumed that in silent mode no questions are asked. If you only set -u then in silent mode everything goes fine - the system will ask for a password and it will get set, however if you do not set -u then, at least on Ubuntu 18.04, the login prompt refuses to set username and the connection fails.
If you use -u but nit set silent mode then the username will be prefilled in the prompt. -p will be disregarded in such a case.

**Comment by ikreb7** [comment]
I think the solution is fine. I mentioned something at the last commit and if this is fixed I am happy that I could your new version.

It's also nice that the you fixed the syntax with ``pep8``. ``flake8, ``isort`` and ``pylint``! Now the code is very nice readable.

**Comment by twoln** [comment]
This still requires some work for the TLS silent install. Will get this done ASAP.

**Comment by ikreb7** [comment]
You can close this PR.

**Pull request closed without merging**
