### PR TITLE
Replace oppressive language

### PR DESCRIPTION
**Pull request by jornane**
In line with changes made in simplesamlphp/simplesamlphp#1351, the usage of the word "master" in the CAT source code is best to be avoided in the light of awareness around #BLM and non-discriminating word choices.

CAT uses the term Master for the Master configuration file, and in the Windows device modules. This pull request aims to replace the word Master with Main. Backwards compatibility with existing deployments is kept by defining an inline Main class that inherits from the Master class, in case Main is not defined but Master is.

### CODE REVIEW

**Comment by restena-sw** [comment]
I firmly believe every human is created equal and has the exact same rights.

This issue is not related to humans at all though. None of the changes have an effect on end users of the software. The only ones reading the code or dealing with the config files are developers and deployers.

I have not remotely heard any complaints about this before from either developers or deployers. So I wonder: do you personally feel that this is something in need of addressing, or is it just about proactively doing something someone somewhere sometime might feel bad about? IMHO and very personally, I would find the latter unwarranted actionism, considering that we are talking about code.

After reading the PR, I was looking up the connotations of the word 'master' in IT by anecdotal web searches. It is certainly well-accepted that the terminology "master/slave" is producing bad feelings and should be avoided. I particularly liked this opinion: https://www.theserverside.com/opinion/Master-slave-terminology-alternatives-you-can-use-right-now

But that same document also states that 'master' alone is much less badly connotated and its use is much less offensive (i.e. the 'slave' part of the combined use is). It even suggests things like 'master/mason' as an acceptable alternative to 'master/slave', implying that there is nothing overly bad in the term master itself.

Do you feel that the word 'master' alone is already offensive and should be redacted?

In particular, in our case at hand, the term 'master' is used in juxtaposition with Master/ConfAssistant and Master/Diagnostics to express the dependency of the two config files. As per the above link, this would likely be considered perfectly acceptable even by people who care much about the subject matter.

In the end, and thinking pragmatically, I concur with many other developer voices I found while searching: it's just a rename of a class; if it doesn't break anything and has the potential to make people happier then why not just do it.

So, if you feel that 'master' should be avoided even if not used together with 'slave', then let's carry on.

In that case, I'm afraid the PR itself is technically not in a good shape. It does several things in one go, and also touches automatically generated documentation. If you want to pursue this further, please create separate PRs for 

- your commits 97c044a112aeb275479e4011e195add4c4daba5a and dda5a7179781f75ee9aad4cc90d6d78e22f21294 but WITHOUT the directory apidoc/ - apidoc is generated by PhpDocumentor and will be fixed on the next PhpDocumentor run (it is only commited to the repo because one needs the PhpDocumentor 3.0 alpha 3 or higher which is quirky and is not present on a typical dev box)

- your commit 41fd983b6dbc6a6418e1d613c3678515b8e70b88  , again without the apidoc/ parts

- since this code change is not in branch_2_0, nobody is considered to have deployed it in production yet, and a backwards compatibility is not necessary. I.e. no need to consider commit 60b77aded2b87625e100998d76af43615de08cb9

**Comment by jornane** [comment]
There seems to be a momentum towards deprecating the term "master", even if used alone. Even [GitHub seems to consider renaming the default git branch](https://twitter.com/natfriedman/status/1271253144442253312).

My personal take on this is that the word "master" can have negative associations for some people. I see from multiple sources that it is not an acceptable term, and I see projects around me shifting their code (so far I've linked SimpleSAMLphp and Github, but there are far more). People that find the term "master" offensive may not have complained to you because there are not so many of them in our "click" yet. Making a change like this shows we take this seriously, and it might make the project more inclusive as a result.

I will make the changes to the PR you requested, but for clarification: Do I understand correctly that you prefer two separate pull requests for this, one for renaming `config\Master` to `config\Main` and one for replacing `master` with `main` in the Windows device configurator generator?

**Comment by restena-sw** [comment]
Well, then why not.

Indeed, one for confg/Master and one for the Windows device.

**Comment by twoln** [comment]
Don't bother with Windows, it will be easier for me to change this myself.

**Pull request merged**
