### PR TITLE
Implemented tkinter graphics on Linux

### PR DESCRIPTION
**Pull request by sdasda7777**
The tkinter library is very common and supports all the same features that yad does.

### CODE REVIEW

**Comment by sdasda7777** [comment]
Note that the diff seems to be misleading at some places.

**Comment by twoln** [comment]
This is really great. I see just one small problem. On the final screen where you ask for credentials there is a Login button for confirmation with the "Login" text hard-coded. If it is not possible to call a system "OK" button like in other commands, then could you please add
ok = "OK" to the Messages class and just use it instead of the Login. I will then add a definition to DeviceLinux.php so we can use a translation of this OK (might be necessary for non-latin languages). 
Other than that all looks great an I will be able to merge.

**Comment by sdasda7777** [comment]
I see, I forgot about that. Unfortunately, I wasn't able to find any way to load this from the locale. I will add the string, of course.

**Comment by sdasda7777** [comment]
Thanks!

**Comment by twoln** [comment]
I have run some tests. Are you sure that tinker should be preferred over zenity? The look of zenity seems to be so much nicer. I would say zenity, tkinter, dialog, tty

**Comment by sdasda7777** [comment]
> Are you sure that tinker should be preferred over zenity?

I personally don't care about this too much, and I think in practice both would work. However I should note that tkinter is technically more robust, as it returns the user input exactly as it was given, whereas reading zenity and yad correctly depends on user not entering a specific sequence into any given field (currently it's 5 consecutive newlines, if I recall correctly).

**Pull request merged**
